### ISSUE TITLE
Vulcanize fails when referencing object outside of component declaration

### ISSUE THREAD

**Issue by positlabs** [Polymer/vulcanize#204]
I'm using `gulp-vulcanize` to process my components, and for some reason it's failing when I try to assemble an object that gets passed to `Polymer()`. Is there a good reason for this? It works at browser runtime, but fails when I try to vulcanize.

```html
<dom-module id="m-actions">

	<style></style>
	<template></template>

	<script>

		var props = {};
		
		Polymer({
			is: "m-actions",
			properties: props
		});
	</script>

</dom-module>
```

Here's the output from the terminal. `NaN:NaN` makes me think it's a bug.

```bash

[12:33:34] Starting 'vulcanize'...
/Volumes/space/workspace/LPLMercury/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/analyzer.js:298
      throw new Error(message);
            ^
Error: Error parsing script in /Volumes/space/workspace/LPLMercury/polymer-app/components/m-actions.html at NaN:NaN
undefined
    at Analyzer._processScript (/Volumes/space/workspace/LPLMercury/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/analyzer.js:298:13)
    at Analyzer.<anonymous> (/Volumes/space/workspace/LPLMercury/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/analyzer.js:273:30)
    at Array.forEach (native)
    at Analyzer._processScripts (/Volumes/space/workspace/LPLMercury/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/analyzer.js:272:11)
    at Analyzer._parseHTML (/Volumes/space/workspace/LPLMercury/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/analyzer.js:231:27)
    at Analyzer.<anonymous> (/Volumes/space/workspace/LPLMercury/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/analyzer.js:201:22)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by garlicnation** [comment]
This should be fixed with the latest hydrolysis release.

**Comment by positlabs** [comment]
Does the hydrolysis version number need to be updated in vulcanize's package.json? When can I test?

**Comment by garlicnation** [comment]
Install vulcanize#hy15 to test.
