### ISSUE TITLE
Fails with parse error when using <script> tag to embed data

### ISSUE THREAD

**Issue by tehsenaus** [Polymer/vulcanize#228]
I'm embedding some data into my page with script tags, like below:
```
<script type="text/csv" id="fx-events-mapping">
... data...
</script>
```

Since updating vulcanize to the latest version, the build no longer works. It seems it is trying to parse the script, even though the type is marked as "text/csv".

```
Error: Error parsing script in /components/events-table/events-table.html at 219:298
Unexpected identifier
  at Analyzer._processScript (c:\Workspace\hv\ui\node_modules\grunt-vulcanize\node_modules\vulcanize\node_modules\hydrolysis\lib\analyzer.js:319:13)
  at Analyzer.<anonymous> (c:\Workspace\hv\ui\node_modules\grunt-vulcanize\node_modules\vulcanize\node_modules\hydrolysis\lib\analyzer.js:294:30)
  at Array.forEach (native)
  at Analyzer._processScripts (c:\Workspace\hv\ui\node_modules\grunt-vulcanize\node_modules\vulcanize\node_modules\hydrolysis\lib\analyzer.js:293:11)
  at Analyzer._parseHTML (c:\Workspace\hv\ui\node_modules\grunt-vulcanize\node_modules\vulcanize\node_modules\hydrolysis\lib\analyzer.js:240:27)
  at Analyzer.<anonymous> (c:\Workspace\hv\ui\node_modules\grunt-vulcanize\node_modules\vulcanize\node_modules\hydrolysis\lib\analyzer.js:210:22)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by azakus** [comment]
This is actually a bug in hydrolysis w.r.t trying to parse any script tag as javascript.

**Comment by azakus** [comment]
This issue was moved to Polymer/hydrolysis#152
