### ISSUE TITLE
Gulp Vulcanize - TypeError: Object #<Object> has no method 'isIdentifierStart'

### ISSUE THREAD

**Issue by ConAntonakos** [Polymer/vulcanize#264]
All of a sudden I started to get this error now when I try to vulcanize a HTML import file:
```

TypeError: Object #<Object> has no method 'isIdentifierStart'
    at parseName (/home/con/repos/admin_dashboard/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/doctrine/lib/doctrine.js:312:31)
    at TagParser._parseNamePath (/home/con/repos/admin_dashboard/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/doctrine/lib/doctrine.js:441:20)
    at TagParser.parseNamePathOptional (/home/con/repos/admin_dashboard/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/doctrine/lib/doctrine.js:458:25)
    at TagParser.parse (/home/con/repos/admin_dashboard/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/doctrine/lib/doctrine.js:695:34)
    at parseTag (/home/con/repos/admin_dashboard/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/doctrine/lib/doctrine.js:718:27)
    at Object.parse (/home/con/repos/admin_dashboard/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/doctrine/lib/doctrine.js:787:23)
    at Object.parseJsdoc (/home/con/repos/admin_dashboard/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/ast-utils/jsdoc.js:158:20)
    at /home/con/repos/admin_dashboard/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/ast-utils/docs.js:400:24
    at Array.forEach (native)
    at Object.parsePseudoElements (/home/con/repos/admin_dashboard/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/ast-utils/docs.js:399:12)

```

The file contains the following: 
```

<link rel="import" href="../bower_components/paper-button/paper-button.html">
<link rel="import" href="../bower_components/paper-dialog/paper-dialog.html">
<link rel="import" href="../bower_components/paper-spinner/paper-spinner.html">
<link rel="import" href="../bower_components/neon-animation/animations/scale-up-animation.html">
<link rel="import" href="../bower_components/neon-animation/animations/fade-out-animation.html">

```

I deduced that it was the paper button HTML import file that was causing the issue, but I don't know why.

My bower.json dependencies:
```

  "dependencies": {
    "polymer": "Polymer/polymer#~1.1",
    "font-awesome": "~4.4.0",
    "es5-shim": "~4.1.7",
    "paper-elements": "PolymerElements/paper-elements",
    "html5shiv": "~3.7.3",
    "foundation": "~5.5.2",
    "typeahead.js": "~0.11.1"
  }

```

**Comment by korzio** [comment]
I've just tried to reproduce it - it works fine with the latest npm vulcanize package and form that repo itself on your example.
