### ISSUE TITLE
Missing closing tag explodes Vulcanize with useless error message

### ISSUE THREAD

**Issue by ktiedt** [Polymer/vulcanize#267]
Something better than the below would be amazing :)

```
TypeError: Cannot read property 'script' of null
    at Analyzer._parseHTML (/build/work/319e33011c700d66658bec8bb007b4d2/google3/blaze-out/host/bin/third_party/javascript/node_modules/vulcanize/bin2.runfiles/google3/third_party/javascript/node_modules/vulcanize/1_14_0/node_modules/hydrolysis/lib/analyzer.js:271:13)
    at Analyzer.<anonymous> (/build/work/319e33011c700d66658bec8bb007b4d2/google3/blaze-out/host/bin/third_party/javascript/node_modules/vulcanize/bin2.runfiles/google3/third_party/javascript/node_modules/vulcanize/1_14_0/node_modules/hydrolysis/lib/analyzer.js:239:22)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by wesalvaro** [comment]
To add some more context, I just ran into this, as well with:

```js
<ul>
  <li>Foo
  <li>Bar
</ul>
```

In this case, it's not just that the missing tag gives a useless error, but [no
closing tag is required](https://www.w3.org/TR/html-markup/li.html) for `<li>`.

Here is the output I got:

```
[TypeError: Cannot read property 'end' of undefined]
[TypeError: Cannot read property 'end' of undefined]
Error processing document at /foo.html
Error processing document at /foo.html
bin/vulcanize failed TypeError: Cannot read property 'script' of null
    at Analyzer._parseHTML (/path/node_modules/vulcanize/vulcanize/node_modules/hydrolysis/lib/analyzer.js:132:19)
    at null._onTimeout (/node_modules/vulcanize/vulcanize/node_modules/hydrolysis/lib/analyzer.js:96:38)
    at Timer.listOnTimeout (timers.js:92:15)
```
