### ISSUE TITLE
vulcanize fails for starter kit

### ISSUE THREAD

**Issue by pharacyde** [Polymer/vulcanize#278]
When running a clean install of the starter kit I receive following exception when executing the vulcanize gulp task

[22:18:54] Starting 'vulcanize'...
[22:18:55] Error in plugin 'gulp-vulcanize'
Message:
    Error parsing script in /private/tmp/polymer-starter-kit-1.1.1/dist/bower_components/iron-selector/iron-selectable.html at NaN:NaN
TypeError: Cannot read property 'push' of undefined
    at Object.observers (/private/tmp/polymer-starter-kit-1.1.1/node_modules/hydrolysis/lib/ast-utils/declaration-property-handlers.js:59:30)
    at Object.visitors.enterObjectExpression (/private/tmp/polymer-starter-kit-1.1.1/node_modules/hydrolysis/lib/ast-utils/behavior-finder.js:211:33)
    at applyVisitors (/private/tmp/polymer-starter-kit-1.1.1/node_modules/hydrolysis/lib/ast-utils/js-parse.js:28:47)
    at Controller.enter (/private/tmp/polymer-starter-kit-1.1.1/node_modules/hydrolysis/lib/ast-utils/js-parse.js:38:14)
    at Controller.__execute (/private/tmp/polymer-starter-kit-1.1.1/node_modules/estraverse/estraverse.js:395:31)
    at Controller.traverse (/private/tmp/polymer-starter-kit-1.1.1/node_modules/estraverse/estraverse.js:493:28)
    at Object.traverse (/private/tmp/polymer-starter-kit-1.1.1/node_modules/estraverse/estraverse.js:705:27)
    at jsParse (/private/tmp/polymer-starter-kit-1.1.1/node_modules/hydrolysis/lib/ast-utils/js-parse.js:85:14)
    at Analyzer._processScript (/private/tmp/polymer-starter-kit-1.1.1/node_modules/hydrolysis/lib/analyzer.js:384:18)
    at Analyzer.<anonymous> (/private/tmp/polymer-starter-kit-1.1.1/node_modules/hydrolysis/lib/analyzer.js:372:30)
    at Array.forEach (native)
    at Analyzer._processScripts (/private/tmp/polymer-starter-kit-1.1.1/node_modules/hydrolysis/lib/analyzer.js:371:11)
    at Analyzer._parseHTML (/private/tmp/polymer-starter-kit-1.1.1/node_modules/hydrolysis/lib/analyzer.js:301:27)
    at Analyzer.<anonymous> (/private/tmp/polymer-starter-kit-1.1.1/node_modules/hydrolysis/lib/analyzer.js:268:22)
    at Timer.listOnTimeout (timers.js:92:15)
Details:
    fileName: /private/tmp/polymer-starter-kit-1.1.1/dist/index.html

**Comment by pharacyde** [comment]
seems it was a temporary issue
